### ISSUE TITLE
./bin/install fails to build caliopen/frontend

### ISSUE THREAD

**Issue by metathink** [CaliOpen/caliopen-dev#17]
node version: v0.12.0
npm version: 2.5.1
Installation log: http://0bin.net/paste/NWV2XZ4er83qxB1W#SyhTBdg9KtecRkBqoX-4hMVdRLfKOhV68Fg5mLgBeJd
npm-debug log: http://0bin.net/paste/U+z32OoRaZRiK0+-#E4y5ZvRdBYOr6MIO9BPVVLkuMNtNpY8FKl1wreoF3dS
Note: I haven't installed docker before running ./bin/install

**Comment by themouette** [comment]
Docker isn't required for those steps as long as you have node and npm.

From latest travis build, there should be no issue using nodejs 0.12

If you still experiment issues, try to upgrade npm as follow: `npm cache clean -f && npm install -g npm`

**Comment by themouette** [comment]
Feel free to reopen this issue if your problem persist.
