### ISSUE TITLE
Start API ans authorization proxy as part of docker-compose

### ISSUE THREAD

**Issue by themouette** [CaliOpen/caliopen-dev#27]
Currently, `start` script runs services on development machine. this require all dependencies to be installed locally (Node, python...).

Using containers make the process more reproducible.

Docker-compose is already here, we can leverage it to start all services in dev mode.

**Comment by gdchamal** [comment]
Yes, surely but ther is many more important things before this kind of docker stuff. It take more time to maintain their folky versioning way of doing than being really efficient in our matters...

**Comment by gdchamal** [comment]
Should invalidate #30 but did not get time to put caliopen.api into a docker image

**Comment by ziir** [comment]
Fixing this should invalidate #28 as well.

**Comment by gdchamal** [comment]
well, start this feature on api side : https://github.com/CaliOpen/caliopen.api/tree/features/docker
