### ISSUE TITLE
depency to nodemon

### ISSUE THREAD

**Issue by esion** [CaliOpen/caliopen-dev#28]
nodemon is not installed on host by default

it could be better to start from npm in order to prevent global install, somethin like this : 

~~~
/**
* packages.json
*/
{ 
  scripts: { 
    start: 'nodemon ...'
 },
  dependancies: {
    nodemon: '...'
  }
}
~~~

~~~
npm start
~~~

**Comment by gdchamal** [comment]
+1

**Comment by ziir** [comment]
Absolutely, I'll take a look tomorrow, thanks for reporting this

**Comment by gdchamal** [comment]
@ziir is it fixed ?

**Comment by esion** [comment]
nodemon is no more required in this repository since docker-compose use start:watch scripts from caliopen.web cf. #38
