### ISSUE TITLE
load-fixture fail due to incomplete configuration

### ISSUE THREAD

**Issue by ncoden** [CaliOpen/caliopen-dev#39]
*cross-repo issue. I post it where the problem is made visible, instead of where it can be solved*

**./load-fixture fail to connect to elasticsearch. "elasticsearch.url" isn't defined.**
*I can't give the logs. I've locally solved the problem, and I can't delete the datas in database to reproduce it, even by deleting .data. http://pastebin.com/QCZeV5vr*

The configuration is used in :
- [base/caliopen/base/store/model.py:60](https://github.com/CaliOpen/caliopen.base/blob/272c4155994a7236c9542d53a43d8cc5e766ac8b/caliopen/base/store/model.py#L60)
- [base.user/caliopen/base/user/store/user.py:99](https://github.com/CaliOpen/caliopen.base.user/blob/9c7aeeadc8751bb3f969401838fb6d35a2a77d05/caliopen/base/user/store/user.py#L99)

elasticsearch.url should be added in [base/caliopen.yaml.template](https://github.com/CaliOpen/caliopen.base/blob/master/caliopen.yaml.template)

**Comment by esion** [comment]
ok for me we can close

**Comment by ncoden** [comment]
fixed
https://github.com/CaliOpen/caliopen.api/commit/73045013a5e7fff1636744b8c1c094a715cd1839
