### ISSUE TITLE
pip is a dependency, too

### ISSUE THREAD

**Issue by bortzmeyer** [CaliOpen/caliopen-dev#41]
% ./bin/install
...
pip and python are required to install locally.

Indeed, python-pip (on Debian) or its equivalent, is necessary, but is not listed in https://caliopen.github.io/ "Requirments"

**Comment by esion** [comment]
pip and python should not be required anymore since PR #40 removes this dependencies. 

I leave this issue open until #40 is merged and to remember that we need to update this documentation.

PS: thank you for the feedback

**Comment by iamdey** [comment]
documentation is in progress CaliOpen/caliopen.github.io#7
