### ISSUE TITLE
Add a oneliner install

### ISSUE THREAD

**Issue by themouette** [CaliOpen/caliopen-dev#5]
That would be great.

Up to now, dependencies must be installed manually.

``` sh
mkdir install-test ; cd $_ ; \
    git clone https://github.com/CaliOpen/caliopen-dev.git bin ; \
    ./bin/install ; \
    ./bin/start
```

**Comment by gdchamal** [comment]
We may enhance later with such capability. python and node dependencies are 2 distincts things and a oneline is may not well suited.
