### ISSUE TITLE
Add test script

### ISSUE THREAD

**Issue by themouette** [CaliOpen/caliopen-dev#6]
Add a script to launch all tests.

This might be divided in several scripts, such as `test-ci`, `test-unit`, `test-functional`...

**Comment by themouette** [comment]
Maybe use http://wercker.com/ ?

**Comment by gdchamal** [comment]
I'm not big fan, for this project, to use too many external tools. and deployment that permit wercker  is out of scope for our need.

But testing must be done, if it can handle testing using docker containers managed with fig it can be useful for the moment (I began to wrote such tests on backend part : https://github.com/gdchamal/caliopen.core/blob/features/strict_interfaces/caliopen%2Ftests)

I think we will have to build our own git, test and deployment platform later when project will be more mature. Nature of this project need for us to ensure full management of development chain and so platform.

So why not for the moment, but don't tie to this service too much, we will have to think our own at a moment, I expect.

**Comment by themouette** [comment]
Sure, you're right.
